# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
#en:
#  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: ä¼ 
#        url: '#about'
#        weight: 1
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en
  staticDir: static
  title: SHUD Group
  params:
    description: SHUD Group
  menu:
    main:
      - name: Home
        url: '#home'
        weight: 1
      - name: Project
        url: 'project'
        weight: 20
      - name: People
        url: 'team'
        weight: 30
      - name: Publications
        url: 'publication'
        weight: 40
      - name: Course
        url: 'course/'
        weight: 70
      - name: SHUD ModelğŸ“š
        url: '../Book_EN'
        weight: 73
      - name: Open Fundingâ­
        url: '../openfunding/'
        weight: 75
      - name: External-Link
        weight: 90
        identifier: externallink
      - name: Global Hydro CloudğŸŒ
        url: 'https://ghdc.ac.cn'
        weight: 1
        parent: externallink
      - name: GalleryğŸ–¼ï¸
        url: 'https://shudapp.netlify.app'
        weight: 2
        parent: externallink
      - name: Join Us
        url: 'opp'
        weight: 99

# Uncomment the lines below to configure your website in a second language.
zh:
  languageCode: zh-CN
  contentDir: content/zh
  staticDir: static
  title: SHUDç ”ç©¶ç»„
  params:
    description: SHUDç ”ç©¶ç»„

  menu:
    main:
      - name: é¦–é¡µ
        url: '#home'
        weight: 1
      - name: é¡¹ç›®
        url: 'project'
        weight: 20
      - name: å›¢é˜Ÿ
        url: 'team/'
        weight: 30
      - name: è®ºæ–‡
        url: 'publication/'
        weight: 50
      - name: ä¹¦ç±/è¯¾ç¨‹
        url: 'course/'
        weight: 70
      - name: SHUDæ¨¡å‹ğŸ“š
        url: '../Book_CN/'
        weight: 73
      - name: å¼€æ”¾åŸºé‡‘â­
        url: '../openfunding/'
        weight: 75
      - name: ExternalLink
        weight: 90
        identifier: externallink
      - name: å…¨çƒæ°´æ–‡æ•°æ®äº‘ğŸŒ
        url: https://ghdc.ac.cn
        weight: 1
        parent: externallink
      - name: SHUDå›¾åº“ğŸ–¼ï¸
        url: https://shudapp.netlify.app
        weight: 2
        parent: externallink
      - name: åŠ å…¥æˆ‘ä»¬
        url: 'opp/'
        weight: 99
